@startuml
'https://plantuml.com/sequence-diagram

participant "ConsultationCommand" as ConsultCmd
participant "DateTimeFormatterUtil" as Formatter
participant "Consultation" as Consultation
participant "TaskList" as TaskList
participant "System" as Console

 -> ConsultCmd : execute(parts, taskList)
activate ConsultCmd

loop until valid input
    alt missing "/from" or "/to"
        ConsultCmd -> Console : println(error)
        activate Console
        Console --> User : prompt for new input
        deactivate Console
        -> ConsultCmd : provide new parts
    else invalid datetime
        ConsultCmd -> Formatter : isValidDateTime(from)
        activate Formatter
        Formatter --> ConsultCmd : true/false
        deactivate Formatter

        ConsultCmd -> Formatter : isValidDateTime(to)
        activate Formatter
        Formatter --> ConsultCmd : true/false
        deactivate Formatter

        alt either is invalid
            ConsultCmd -> Console : println(error)
            activate Console
            Console --> User : prompt for new input
            deactivate Console
            User -> ConsultCmd : provide new parts
        end
    else valid input
        create Consultation
        ConsultCmd -> Consultation : new(studentName, false, from, to)
        activate Consultation
        Consultation --> ConsultCmd
        deactivate Consultation

        ConsultCmd -> TaskList : addTask(consultation)
        activate TaskList
        deactivate TaskList
    end
end

deactivate ConsultCmd
@enduml