@startuml
'https://plantuml.com/sequence-diagram

actor User

participant "MarkTaskCommand" as MarkCmd
participant "IntegerChecker" as Checker
participant "TaskList" as TaskList
participant "System" as Console

User -> MarkCmd : execute(parts, taskList)
activate MarkCmd

MarkCmd -> Checker : isInteger(parts)
activate Checker
Checker --> MarkCmd
deactivate Checker

alt valid integer
    MarkCmd -> TaskList : markTaskAsDone(Integer.parseInt(parts))
    activate TaskList
    deactivate TaskList
else invalid input
    MarkCmd -> MarkCmd : throw TASyncException
    MarkCmd -> Console : println(e.getMessage())
    activate Console
    deactivate Console
end

deactivate MarkCmd
@enduml