@startuml
'https://plantuml.com/sequence-diagram

participant "TodoCommand" as TodoCmd
participant "TaskList" as TaskList
participant "Todo" as Todo

-> TodoCmd : execute(parts, taskList)
activate TodoCmd

alt parts is not empty
    create Todo
    TodoCmd -> Todo : new Todo(parts, false)
    activate Todo
    Todo --> TodoCmd
    deactivate Todo

    TodoCmd -> TaskList : addTask(todo)
    activate TaskList
    deactivate TaskList
end

deactivate TodoCmd
@enduml