@startuml


participant "DeleteTutorialCommand" as DTC
participant "tutorialClassList: TutorialClassList" as TCL

-> DTC: execute(input, tutorialClassList)
activate DTC


    DTC -> TCL: getTutorialByName(input)
    activate TCL
    TCL --> DTC: return TutorialClass
    deactivate TCL



    alt tutorial exists
        DTC -> TCL: removeTutorialClass(tutorialClass)
        activate TCL
        TCL --> DTC: void
        deactivate TCL
    end


deactivate DTC

@enduml
