@startuml

actor User

participant "ListExistingTutorialsCommand" as LETC
participant "TutorialClassList" as TCL
participant "tutorialClasses: ArrayList<TutorialClass>" as List
participant "TutorialClass" as TC

User -> LETC: execute(input, tutorialClassList)
activate LETC

LETC -> TCL: getTutorialClasses()
activate TCL
TCL --> LETC: tutorialClasses
deactivate TCL

alt tutorialClasses is empty
    LETC -> User: print "There are no tutorials created yet."
else
    LETC -> List: sort by day and then time
    activate List
    List --> LETC: return sorted tutorials
    deactivate List

    LETC -> User: print "Existing Tutorials:"

    loop for each tutorial
        LETC -> TC: getTutorialName()
        LETC -> TC: getDayOfWeek()
        LETC -> TC: getStartTime()
        LETC -> TC: getEndTime()
        LETC -> User: print tutorial details
    end

    LETC -> User: print "End of list"
end

deactivate LETC

@enduml
