@startuml


participant "ListExistingTutorialsCommand" as LETC
participant "tutorialClassList: TutorialClassList" as TCL
participant "tutorialClasses: ArrayList<TutorialClass>" as List
participant "TutorialClass" as TC

-> LETC: execute(input, tutorialClassList)
activate LETC

LETC -> TCL: getTutorialClasses()
activate TCL
TCL --> LETC: return tutorialClasses
deactivate TCL


    LETC -> List: sort by day and then time
    activate List
    List --> LETC: return sorted tutorials
    deactivate List

    loop for each tutorial
        LETC -> TC: getTutorialName()
        TC --> LETC: tutorial name
        activate TC
        LETC -> TC: getDayOfWeek()
        TC --> LETC: day of week
        LETC -> TC: getStartTime()
        TC --> LETC: start time of tutorial
        LETC -> TC: getEndTime()
        TC --> LETC: end time of tutorial
        deactivate TC
    end


deactivate LETC

@enduml
