@startuml
participant "NewTutorialCommand" as Command
participant "StudentCommandHelper" as Helper
participant "TutorialClassList" as List
participant "TutorialClass" as Tutorial

-> Command: execute(input, tutorialClassList)

activate Command

Command -> Helper: parseInput(input, 4)
Helper --> Command: String[] inputParts

create Tutorial
Command -> Tutorial: new TutorialClass(name, dayOfWeek, startTime, endTime)
activate Tutorial
Tutorial -> Command: new tutorial
deactivate Tutorial

Command -> List: addTutorialClass(newTutorial)


deactivate Command
@enduml
