@startuml
'https://plantuml.com/sequence-diagram
actor user
autonumber

participant "CommentOnStudent: Command<Attendancefile>" as command
participant "parts: String" as parts
participant "partsArray2: String[]" as partsArray
participant "comments : java.util.ArrayList" as comments
participant "comment : java.lang.String" as comment
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "theOne : AttendanceList" as theOne
participant "StudentList" as studentList
participant "TutorialClass" as tutorialClass
participant "e : TASyncException" as e
participant "n : NumberFormatException" as n


skinparam sequenceReferenceBackgroundColor #f7807c
skinparam sequenceAltBackgroundColor #f7807c


user -> command : execute(parts : String, target : T)
activate command
alt try

    command -> parts : split("//")
    activate parts
    parts --> command : partsArray2
    deactivate parts
    command -> partsArray : partsArray2[0].split(",")
    activate partsArray
    command <-- partsArray : partsArray
    deactivate partsArray
    command -> partsArray : partsArray2[1].split(";")
    activate partsArray
    command <-- partsArray : commentsArray
    deactivate partsArray
    create comments
    command -> comments
    activate comments

    loop for each commentsArray
    command -> comments : add(comment.trim())
    command -> comment : trim()
    end loop

ref over command, listOfAttendanceList, theOne, tutorialClass, studentList
find student in tutorial
end ref


    command -> theOne : addComments(student : Student = derStudent, comments : ArrayList<String> = comments) : void
    activate theOne
    command --> user : print the comments added
    deactivate comments

deactivate theOne
    command -> e : e.getMessage()
        activate e
        e --> command : return error message
        deactivate e
        command --> user  : print error message

        else catch NumberFormatException
         command -> n : n.getMessage()
         activate n
         n --> command : return error message
         deactivate n
         command --> user : error message
end
destroy parts
destroy partsArray
destroy comments
destroy comment

@enduml