@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "ShowAttendanceListCommand : Command<AttendanceFile>" as command
participant "partsArray" as parts
participant "attenList : AttendanceList" as attenList
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "listOfTutorials : TutorialClassList" as listOfTutorials



User -> command : execute(parts : String, target : T)
activate command
alt parts is null or empty
command -> command : throw TASyncException()
command --> User : print error message
else second param is non-number string
command -> command : throw NumberFormatException()
command --> User : print error message
else input is valid
create parts
command -> parts : parts.split(",")
activate listOfAttendanceList
command -> listOfAttendanceList : getAttendanceListByNameAndWeek(week,name)
activate listOfTutorials
listOfAttendanceList -> listOfTutorials : check if tut name exists
listOfTutorials --> listOfAttendanceList: returns boolean of if it exists
deactivate listOfTutorials

listOfAttendanceList --> command : returns attendanceList
alt tutorial does not exist
command -> command : throw TASyncException()
command --> User : print error message
else
alt the attendanceList is null
create attenList
command -> attenList
activate attenList
attenList --> command : it is returned to be stored in local var
deactivate attenList
command -> listOfAttendanceList : listOfAttendanceList.addAttendanceList(attenList)


deactivate listOfAttendanceList
command --> User : print("Attendance list for the week already exists")
else the attendanceList is not null
command --> User : print message stating attendanceList already exists
end alt
end alt
end alt

destroy parts
@enduml