@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "ShowAttendanceListCommand : Command<AttendanceFile>" as command
participant "partsArray" as parts
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "listOfTutorials : TutorialClassList" as listOfTutorials
participant "attenList : AttendanceList" as attenList
participant "e : TASyncException" as e
participant "n : NumberFormatException" as n

User -> command : execute(parts : String, target : T)
activate command
alt try
create parts
command -> parts : parts.split(",")
activate listOfAttendanceList
command -> listOfAttendanceList : getAttendanceListByNameAndWeek(week,name)
activate listOfTutorials
listOfAttendanceList -> listOfTutorials : check if tut name exists
listOfTutorials --> listOfAttendanceList: returns boolean of if it exists
deactivate listOfTutorials

listOfAttendanceList --> command : returns attendanceList
alt the attendanceList is null
create attenList
command -> attenList
activate attenList
attenList --> command : it is returned to be stored in local var
deactivate attenList
command -> listOfAttendanceList : listOfAttendanceList.addAttendanceList(attenList)


deactivate listOfAttendanceList
command --> User : print("Attendance list for the week already exists")
else the attendanceList is not null
command --> User : print message stating attendanceList already exists
end alt

else catch TASyncException


    command -> e : e.getMessage()
        activate e
        e --> command : return error message
        deactivate e
        command --> User  : print error message

        else catch NumberFormatException
         command -> n : n.getMessage()
         activate n
         n --> command : return error message
         deactivate n
         command --> User : error message
end

destroy parts
@enduml