@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "ShowAttendanceListCommand : Command<AttendanceFile>" as command
participant "partsArray" as parts
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "theOne : AttendanceList" as theOne
participant "TutorialClass" as tutorialClass
participant "StudentList" as studentList
participant "e : TASyncException" as e
participant "n : NumberFormatException" as n

skinparam sequenceReferenceBackgroundColor #f7807c

User -> command : execute(parts : String, target : T)
activate command
alt try

create parts
command -> parts : parts.split(",")
activate listOfAttendanceList
ref over command, listOfAttendanceList, theOne, tutorialClass, studentList
find student in tutorial
end ref


activate tutorialClass
activate studentList
activate theOne
command -> theOne : getAttendanceMap()
deactivate listOfAttendanceList
theOne --> command : return attendanceMap

deactivate theOne
deactivate tutorialClass
deactivate studentList
command --> User : print out the attendanceMap\n according to format

else catch TASyncException


    command -> e : e.getMessage()
    activate e
    e --> command : return error message
    deactivate e
    command --> User  : print error message

    else catch NumberFormatException
     command -> n : n.getMessage()
     activate n
     n --> command : return error message
     deactivate n
     command --> User : error message

end
destroy parts


@enduml