@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant "ShowAttendanceListCommand : Command<AttendanceFile>" as command
participant "partsArray" as parts
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "theOne : AttendanceList" as theOne
participant "TutorialClass" as tutorialClass
participant "StudentList" as studentList


skinparam sequenceReferenceBackgroundColor #f7807c

User -> command : execute(parts : String, target : T)
activate command


alt parts null or is empty
command -> command : throw TASyncException()
command --> User : print error message
else second param is non-number string
command -> command : throw NumberFormatException()
command --> User : print error message
else input is valid
create parts
command -> parts : parts.split(",")
activate listOfAttendanceList
ref over User, command, listOfAttendanceList, theOne, tutorialClass, studentList
find student in tutorial
end ref


activate tutorialClass
activate studentList
activate theOne
command -> theOne : getAttendanceMap()
deactivate listOfAttendanceList
theOne --> command : return attendanceMap

deactivate theOne
deactivate tutorialClass
deactivate studentList
command --> User : print out the attendanceMap\n according to format
end

destroy parts


@enduml