@startuml
'https://plantuml.com/sequence-diagram
actor user

participant "CommentOnStudentCommand" as command
participant "parts: String" as parts
participant "partsArray2: String[]" as partsArray
participant "comments : java.util.ArrayList" as comments
participant "comment : java.lang.String" as comment
participant "listOfAttendanceList : AttendanceFile" as listOfAttendanceList
participant "theOne : AttendanceList" as theOne
participant "StudentList" as studentList
participant "TutorialClass" as tutorialClass
participant "e : TASyncException" as e
participant "n : NumberFormatException" as n


skinparam sequenceReferenceBackgroundColor #f7807c
skinparam sequenceAltBackgroundColor #f7807c


user -> command : execute(parts : String, target : T)
activate command

alt try

    command -> parts : split("//")
    parts --> command : partsArray2
    command -> partsArray : partsArray2[0].split(",")
    command <-- partsArray : partsArray
    command -> partsArray : partsArray2[1].split(";")
    command <-- partsArray : commentsArray
    create comments
    command --> comments: message

    loop for each commentsArray
    command -> comments : add(comment.trim())
    command -> comment : trim()
    end loop

ref over command, listOfAttendanceList, theOne, tutorialClass, studentList
get student in Tutorial if have
end ref

    command -> theOne : addComments(student : Student = derStudent, comments : ArrayList<String> = comments) : void

    else catch TASyncException
    command -> e : e.getMessage
    user <-- command : error message

    else catch NumberFormatException
     command -> n : n.getMessage
     user <-- command : error message
    end



'command -> command : split("//")
'command -> command : split(",")
'command -> command : split(";")
'
'loop
'    command -> comment : trim()
'    command -> comments : add(comment.trim())
'end
'
'command -> command : getTutorialClass()
'command -> command : getAttendanceList()
'command -> command : getStudentList()
'command -> command : getStudents()
'
'alt [try]
'    loop for each commentsArray
'        command -> studentList : addComments(student, comments)
'    end
'else [catch TASyncException]
'    e -> e : getMessage()
'end
@enduml