@startuml
actor User

participant "ChangeRemarkCommand" as CRC
participant "TutorialClassList" as TCL
participant "TutorialClass" as TC
participant "StudentList" as SL
participant "Student" as S

User -> CRC: execute(input, tutorialClassList)
activate CRC


CRC -> TCL: getTutorialByName(tutorialClassCode)
activate TCL
TCL --> CRC: return TutorialClass
deactivate TCL

alt tutorial has no start time
    CRC -> User: print "tutorial does not exist"
else
    CRC -> TC: getStudentList()
    activate TC
    TC --> CRC: return StudentList
    deactivate TC

    CRC -> SL: getStudentByMatricNumber(matricNumber)
    activate SL
    alt student not found
        SL --> CRC: return null
        deactivate SL
        CRC -> User: print "No student found"
    else
        SL --> CRC: return Student
        deactivate SL

        CRC -> S: setRemark(newRemark)
        activate S
        S --> CRC: updated remarks
        deactivate S

        CRC -> User: print "Remark updated"
    end
    end

deactivate CRC
@enduml