@startuml

participant "ChangeRemarkCommand" as CRC
participant "StudentCommandHelper" as Helper
participant "tutorialClassList: TutorialClassList" as TCL
participant "TutorialClass" as TC
participant "StudentList" as SL
participant "Student" as S

-> CRC: execute(input, tutorialClassList)
activate CRC

CRC -> Helper: parseInput(input, 3)
activate Helper
Helper --> CRC: String[] inputParts
deactivate Helper

CRC -> TCL: getTutorialByName(tutorialClassCode)
activate TCL
TCL --> CRC: return TutorialClass
deactivate TCL


    CRC -> TC: getStudentList()
    activate TC
    TC --> CRC: return StudentList
    deactivate TC

    CRC -> SL: getStudentByMatricNumber(matricNumber)
    activate SL
        SL --> CRC: return Student
        deactivate SL

        CRC -> S: setRemark(newRemark)
        activate S
        S --> CRC:
        deactivate S


deactivate CRC
@enduml