@startuml


participant "CheckRemarkCommand" as CRC
participant "tutorialClassList: TutorialClassList" as TCL
participant "TutorialClass" as TC
participant "StudentList" as SL
participant "Student" as S

 -> CRC: execute(input,tutorialClassList)
activate CRC

CRC -> TCL: getTutorialByName(tutorialClassCode)
activate TCL
TCL --> CRC: TutorialClass
deactivate TCL



    CRC -> TC: getStudentList()
    activate TC
    TC --> CRC: StudentList
    deactivate TC

    CRC -> SL: getStudentByMatricNumber(matricNumber)
    activate SL
    SL --> CRC: Student
    deactivate SL


        CRC -> S: getRemark()
        activate S
        S --> CRC: remark
        deactivate S


        deactivate CRC

@enduml
