@startuml
actor User

participant "CheckRemarkCommand" as CRC
participant "TutorialClassList" as TCL
participant "TutorialClass" as TC
participant "StudentList" as SL
participant "Student" as S

User -> CRC: execute(input,tutorialClassList)
activate CRC

CRC -> TCL: getTutorialByName(tutorialClassCode)
activate TCL
TCL --> CRC: TutorialClass
deactivate TCL


alt tutorial not found
    CRC -> User: print "Invalid tutorial or input"
    deactivate CRC
else valid tutorial
    CRC -> TC: getStudentList()
    activate TC
    TC --> CRC: StudentList
    deactivate TC

    CRC -> SL: getStudentByMatricNumber(matricNumber)
    activate SL
    SL --> CRC: Student
    deactivate SL

    alt student is null
        CRC -> User: print "Student not found"
        deactivate CRC
    else student found
        CRC -> S: getRemark()
        activate S
        S --> CRC: remark
        deactivate S

        alt remark is null or empty
            CRC -> User: print "No remarks found"
        else
            CRC -> User: print "Remarks: [remark]"
        end
        deactivate CRC
    end
end

@enduml
