@startuml

participant "DeleteStudentCommand" as DSC
participant "StudentCommandHelper" as Helper
participant "tutorialClassList: TutorialClassList" as TCL
participant "TutorialClass" as TC
participant "StudentList" as SL

-> DSC: execute(input, tutorialClassList)
activate DSC

DSC -> Helper: parseInput(input, 2)
activate Helper
DSC --> CRC: String[] inputParts
deactivate Helper

DSC -> TCL: getTutorialByName(tutorialClassCode)
activate TCL
TCL --> DSC: TutorialClass
deactivate TCL


    DSC -> TC: getStudentList()
    activate TC
    TC --> DSC: StudentList
    deactivate TC

    DSC -> SL: getStudentByMatricNumber(matricNumber)
    activate SL
    SL --> DSC: Student
    deactivate SL

    alt student found
        DSC -> SL: removeStudent(student)
        activate SL
        SL --> DSC
        deactivate SL
    end
    deactivate DSC


@enduml
