@startuml

participant "FindStudentCommand" as FSC
participant "tutorialClassList: TutorialClassList" as TCL
participant "ArrayList<TutorialClass>" as TC
participant "StudentList" as SL
participant "Student" as S

-> FSC: execute(keyword, tutorialClassList)
activate FSC

    FSC -> TCL: getTutorialClasses()
    activate TCL
    TCL --> FSC: return ArrayList<TutorialClass>
    deactivate TCL

    loop for each TutorialClass
        FSC -> TC: getStudentList()
        activate TC
        TC --> FSC: StudentList
        deactivate TC

        FSC -> SL: getStudents()
        activate SL
        SL --> FSC: return ArrayList<Student>
        deactivate SL

        loop for each Student
            FSC -> S: check for keyword match
            activate S
            S --> FSC: name, matric number
            deactivate S


        end
    end


    deactivate FSC

@enduml
